package ikame.docxreader.ui;

import org.openqa.selenium.By;

public class PageUI_DocxReader_Scanner {
	public static final By BTN_MULTIPLE = By.xpath("//android.widget.LinearLayout[@content-desc='Multiple']");
	public static final By BTN_TAKE_PHOTO = By.id("com.happydev.wordoffice:id/img_take");
	public static final By TEXT_NUMBER_OF_PHOTO_TAKEN = By.id("com.happydev.wordoffice:id/textImageCount");
	public static final By BTN_NEXT = By.id("com.happydev.wordoffice:id/btnNext");
	public static final By BTN_TOTAL_OF_PHOTO_TAKEN = By.id("com.happydev.wordoffice:id/tv_index");
	public static final By BTN_DONE = By.id("com.happydev.wordoffice:id/btn_Done");
	public static final By BTN_SINGLE = By.xpath("//android.widget.LinearLayout[@content-desc='Single']");
	public static final By ICON_FLASH = By.id("com.happydev.wordoffice:id/ivFlash");
	public static final By BTN_GRID_MODE = By.id("com.happydev.wordoffice:id/img_grid");
	public static final By BTN_GALLERY = By.id("com.happydev.wordoffice:id/btnGallery");
	public static final By TITLE_GALLERY = By.id("com.happydev.wordoffice:id/tvGalleryName");
	public static final By LIST_OF_IMAGES = By.id("com.happydev.wordoffice:id/iv_img");
	public static final By LIST_OF_CHECKBOX_IMAGES = By.id("com.happydev.wordoffice:id/iv_check");
	public static final By BTN_CONFIRM = By.id("com.happydev.wordoffice:id/tv_confirm");
	public static final By DROPDOWN_LIST_IMAGE = By.id("com.happydev.wordoffice:id/ivDownArrow");
	public static final By TEXT_CAMERA = By.xpath("//android.widget.TextView[@text='Camera']");
	public static final By TEXT_SCREENSHOTS = By.xpath("//android.widget.TextView[@text='Screenshots']");
	public static final By TEXT_ALL_IMAGE = By.xpath("//android.widget.TextView[@text='All Image']");
	public static final By BTN_IV_BACK = By.id("com.happydev.wordoffice:id/iv_back");
	public static final By BTN_ADD = By.id("com.happydev.wordoffice:id/btnAddImage");
	public static final By TEXT_FEATURE = By.id("com.happydev.wordoffice:id/tvFeature");
	public static final By TAB_FROM_CAMERA = By.id("com.happydev.wordoffice:id/addIm_fromCamera");
	public static final By TAB_FROM_GALLERY = By.id("com.happydev.wordoffice:id/addIm_fromGallery");
	public static final By BTN_TAKE_PICTURE = By.id("com.happydev.wordoffice:id/btnTakePicture");
	public static final By ICON_CANCEL = By.id("com.happydev.wordoffice:id/btnCancel");
	public static final By ICON_DONE = By.id("com.happydev.wordoffice:id/btnNext");
	public static final By TEXT_SELECT_IMAGES = By.xpath("//android.widget.TextView[@text='Tap to select images']");
	public static final By LIST_IMG = By.id("com.happydev.wordoffice:id/image_view");
	public static final By BTN_NAVIGATE_UP = By.xpath("//android.widget.ImageButton[@content-desc='Navigate up']");
	public static final By BTN_SAVE = By.id("com.happydev.wordoffice:id/tvSave");
	public static final By BTN_RETAKE = By.id("com.happydev.wordoffice:id/btnRetake");
	public static final By BTN_CROP = By.id("com.happydev.wordoffice:id/btnCrop");
	public static final By IMG_CROP = By.id("com.happydev.wordoffice:id/iv_crop");
	public static final By BTN_LEFT = By.id("com.happydev.wordoffice:id/btnRotateLeft");
	public static final By BTN_RIGHT = By.id("com.happydev.wordoffice:id/btnRotateRight");
	public static final By BTN_NO_CROP = By.id("com.happydev.wordoffice:id/btnNoCrop");
	public static final By BTN_AUTO_CROP = By.id("com.happydev.wordoffice:id/btnAutoCrop");
	public static final By BTN_FILTER = By.id("com.happydev.wordoffice:id/btnFilter");
	public static final By LIST_OPTION_FILTER = By.id("com.happydev.wordoffice:id/iv_bg");
	public static final By TEXT_APPLY_TO_ALL_PAGES = By.id("com.happydev.wordoffice:id/tvApplyAllPage");
	public static final By RADIO_BUTTON_APPLY_TO_ALL = By.id("com.happydev.wordoffice:id/btn_allPage");
	public static final By BTN_CANCEL_FILTER = By.id("com.happydev.wordoffice:id/iv_cancel");
	public static final By BTN_DONE_FILTER = By.id("com.happydev.wordoffice:id/btnDoneFilter");
	public static final By BTN_REFLECT = By.id("com.happydev.wordoffice:id/btnFlip");
	public static final By BTN_SIGNATURE = By.id("com.happydev.wordoffice:id/btnSign");
	public static final By SUB_TITLE_SIGNATURE = By.xpath("//android.widget.TextView[@text='Signature']");
	public static final By TEXT_SIGN_HERE = By.id("com.happydev.wordoffice:id/tv_sign_hint");
	public static final By ICON_COLOR = By.id("com.happydev.wordoffice:id/iv_sign_color");
	public static final By ICON_ERASE = By.id("com.happydev.wordoffice:id/iv_erase");
	public static final By ICON_HISTORY = By.id("com.happydev.wordoffice:id/iv_sign_list");
	public static final By BTN_CANCEL_SIGNATURE = By.id("com.happydev.wordoffice:id/tv_signal_cancel");
	public static final By BTN_DONE_SIGNATURE = By.id("com.happydev.wordoffice:id/tv_signal_confirm");
	public static final By ICON_COLOR_BLUE = By.id("com.happydev.wordoffice:id/iv_sign_color_blue");
	public static final By TEXT_NO_FILE_FOUND = By.xpath("//android.widget.TextView[@text='No file found']");
	public static final By IMG_SIGNATURE = By.id("com.happydev.wordoffice:id/iv_item_signature");
	public static final By BTN_DELETE_SIGNATURE = By.id("com.happydev.wordoffice:id/iv_remove");
	public static final By BTN_CONFIRM_DELETE = By.id("com.happydev.wordoffice:id/tv_confirm_delete");
	public static final By ICON_DONE_EDIT_SIGNATURE = By.id("com.happydev.wordoffice:id/iv_done");
	public static final By TEXT_DELETE_CONTENT = By.id("com.happydev.wordoffice:id/tv_delete_content");
	public static final By TEXT_CANCEL_DELETE = By.id("com.happydev.wordoffice:id/tv_cancel_delete");
	public static final By TEXT_DELETE = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_delete_content']//preceding-sibling::android.widget.TextView");
	public static final By BUTTON_DELETE = By.id("com.happydev.wordoffice:id/btnDelete");
	public static final By BTN_IV_RIGHT = By.id("com.happydev.wordoffice:id/iv_right");
	public static final By BUTTON_IV_LEFT = By.id("com.happydev.wordoffice:id/iv_left");
	public static final By BTN_BACK = By.id("com.happydev.wordoffice:id/btnBack");
	public static final By TEXT_DISCARD_CONTENT = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_discard_content']");
	public static final By TEXT_DISCARD = By.xpath("//android.widget.TextView[@resource-id='com.happydev.wordoffice:id/tv_discard_content']//preceding-sibling::android.widget.TextView");
	public static final By BTN_DISCARD = By.id("com.happydev.wordoffice:id/tv_discard");
	public static final By BTN_DISCARD_CANCEL = By.id("com.happydev.wordoffice:id/tv_cancel");
	public static final By TEXTBOX_RENAME = By.id("com.happydev.wordoffice:id/edFileName");
	public static final By BTN_MEDIUM = By.id("com.happydev.wordoffice:id/txtMedium");
	public static final By BTN_SAVE_TO_GALLERY = By.id("com.happydev.wordoffice:id/btnSaveToAlbum");
	public static final By BTN_HOME = By.id("com.happydev.wordoffice:id/btnHome");
	public static final String TEXT_FILE_NAME = "//android.widget.TextView[contains(@text,'&option')]";
	public static final By TEXT_RENAME = By.xpath("//android.widget.TextView[@text='Rename']");
	public static final By TEXT_IMAGE_QUALITY = By.id("com.happydev.wordoffice:id/tvQuality");
	public static final By IMG_FILE = By.id("com.happydev.wordoffice:id/ivPreview");
	public static final By TITLE_FILE_NAME = By.id("com.happydev.wordoffice:id/tvToolbarName");
	public static final By ICON_FULL_SCREEN = By.id("com.happydev.wordoffice:id/btnToolbarFullScreen");
	public static final By BTN_SHARE = By.id("com.happydev.wordoffice:id/btnShare");
	public static final By TEXT_SHARE_FILE = By.id("miuix.stub:id/alertTitle");
	public static final By TEXT_FILE_NAME_SEVED = By.id("android.miui:id/ll_file_type_container");
	public static final By TEXT_PAGE_DISPLAY = By.id("com.happydev.wordoffice:id/pageDisplay");
	public static final By BTN_BACK_VIEW_FILE = By.id("com.happydev.wordoffice:id/btnToolbarBack");
	public static final By TAB_ID_CARDS = By.xpath("//android.widget.LinearLayout[@content-desc='ID Cards']");
	public static final By TAB_DOCUMENT = By.xpath("//android.widget.LinearLayout[@content-desc='Document']");
	public static final By TAB_TO_TEXT = By.xpath("//android.widget.LinearLayout[@content-desc='To Text']");
	public static final By COMBO_BOX_SELECT_LANGUAGE = By.id("com.happydev.wordoffice:id/ln_pick_language");
	public static final By OPTION_LANGUAGE = By.xpath("//android.widget.RadioButton[@resource-id='com.happydev.wordoffice:id/rb_select']");
	public static final By TEXT_RECOGNIZE = By.xpath("//android.widget.TextView[@text='Text Recognize']");
	public static final By TEXT_FINISH = By.id("com.happydev.wordoffice:id/tv_finish");
	public static final By TEXT_RESULT = By.xpath("//android.widget.TextView[@text='Result']");
	public static final By TEXT_CANNOT_RECOGNIZE = By.id("com.happydev.wordoffice:id/ed_result");
	public static final By BTN_COPY = By.id("com.happydev.wordoffice:id/ln_copy");
	public static final By BTN_EDIT = By.id("com.happydev.wordoffice:id/ln_edit");
	public static final By TEXT_SHARE = By.id("com.happydev.wordoffice:id/ln_share");
	public static final By TAB_CONFIRM = By.id("com.happydev.wordoffice:id/dlg_edittext_confirm");
	public static final By TEXT_CREATING_PDF = By.id("com.happydev.wordoffice:id/dlg_edittext_title");
	public static final By TEXTBOX_ENTER_FILE_NAME = By.id("com.happydev.wordoffice:id/dlg_edittext_text");
	public static final By BTN_CANCEL = By.id("com.happydev.wordoffice:id/dlg_edittext_cancel");
	public static final By TAB_QR_CODE = By.xpath("//android.widget.LinearLayout[@content-desc='QR Code']");
	public static final By IMG_CAMERA_SCAN_LINE = By.id("com.happydev.wordoffice:id/fragmentCameraQRCode_cameraScanLine");
	public static final By BTN_CANCEL_QR_CODE = By.id("com.happydev.wordoffice:id/fragmentCameraQRCode_tvCancel");
}
